const translations = {
  es: {
    inicio: "Inicio",
    sobre: "Sobre mí",
    habilidades: "Habilidades",
    proyectos: "Proyectos",
    certificaciones: "Certificaciones",
    contacto: "Contacto",
    desarroladorst: "Desarrollador de software junior.",
    desarroladorDesc: "Construyendo backends confiables y sistemas limpios, una línea depurada a la vez.",
    quiensoyst: "Sobre mí",
    descripQuiensoyst: "Desarrollador enfocado en construir sistemas limpios, resolver problemas y convertir datos en decisiones.",
    añosprog: "Años programando",
    projecCompl: "Proyectos completados",
    lenguajesCard: "Lenguajes usados",
    certificacionesCard: "Certificaciones",
    descrip1: "Soy un desarrollador web juni/or con un enfoque orientado al backend y experiencia en ASP.NET Core, PHP/Laravel, SQL y redes informáticas. Disfruto creando sistemas organizados, resolviendo problemas y comprendiendo el funcionamiento interno detrás del código.",
    descrip2: "También me interesan la ciencia de datos, la visualización de datos y los mercados financieros. Como trader e inversor en acciones y criptomonedas, he reforzado mi interés por los datos, el análisis, los patrones y la toma de decisiones.",
    descrip3: "Disfruto combinando el desarrollo de software, las redes, los datos y las finanzas en mis proyectos personales, mientras continúo mejorando mis habilidades y creciendo como desarrollador.",
    conQueTrabajo: "Con qué trabajo",
    lenguajesStack: "Lenguajes",
    dbtext: "Bases de datos",
    herram: "Herramientas",
    cienciaDatos: "Ciencia de datos",
    loQueHe: "Lo que he creado",
    proyectos: "Proyectos",
    proj1: "Proyecto académico EbaisSys",
    descProj1: "Aplicación web para la gestión básica de un EBAIS...",
    verMasProj: "Ver más",
    verGithub: "Ver en Github",
    proj1desc1: "Desarrollé una aplicación web para la gestión básica de un EBAIS, permitiendo administrar pacientes y procesos administrativos de manera sencilla y organizada.",
    proj1desc2: "El sistema implementa operaciones CRUD con validaciones para garantizar la correcta gestión de la información y mantener la integridad de los datos.",
    proj1desc3: "La aplicación sigue la arquitectura MVC, ofreciendo una estructura de código limpia, escalable y fácil de mantener.",
    proj2: "Proyecto académico Expotecnica",
    descProj2: "Aplicación web para gestionar y evaluar proyectos de ExpoTécnica...",
    proj2desc1: "Desarrollé una aplicación web en ASP.NET Core y SQL Server para gestionar y evaluar proyectos de ExpoTécnica, facilitando el proceso de calificación por categorías.",
    proj2desc2: "El sistema permite registrar evaluaciones, asignar puntuaciones y visualizar los resultados de forma clara y organizada para los jueces.",
    proj2desc3: "La aplicación fue desplegada en Azure con una base de datos en la nube, permitiendo el acceso remoto desde cualquier dispositivo.",
    proj3: "Sistema TradeForGod (Proyecto real)",
    descProj3: "Sistema web en PHP con arquitectura MVC integrado con Discord...",
    proj3desc1: "Desarrollé un sistema web en PHP con arquitectura MVC para gestionar usuarios, grupos, pagos y diferentes procesos internos mediante un sistema de roles.",
    proj3desc2: "Cuenta con roles de Administrador, Profesor y Estudiante, además de autenticación, control de acceso e integración con Discord para la gestión de usuarios.",
    proj3desc3: "Actualmente, el proyecto se encuentra en proceso de migración a Laravel, buscando mejorar su escalabilidad, mantenimiento y estructura.",
    proj4: "Sistema de gestión de ventas e inventario",
    descProj4: "Sistema de gestión de inventario y ventas en C++ con arrays...",
    proj4desc1: "Desarrollé un sistema de gestión de inventario y ventas en C++, enfocado en administrar productos, proveedores, usuarios y clientes.",
    proj4desc2: "El sistema implementa operaciones CRUD y un flujo de ventas funcional, incluyendo la actualización automática del stock disponible.",
    proj4desc3: "Cuenta con una interfaz de consola y manejo de datos mediante arreglos, simulando procesos básicos de un negocio.",
    proj5: "Proyecto de infraestructura de red",
    descProj5: "Infraestructura de red empresarial en Cisco Packet Tracer...",
    proj5desc1: "Desarrollé una infraestructura de red empresarial en Cisco Packet Tracer, simulando la conexión de dos sedes con un proveedor de servicios de Internet.",
    proj5desc2: "La red implementa segmentación mediante VLAN, enrutamiento estático y el protocolo HSRP para garantizar alta disponibilidad y continuidad del servicio.",
    proj5desc3: "El proyecto incluye el diseño del direccionamiento IP, la configuración completa de la red y su documentación técnica para facilitar su implementación.",
    proj6: "Sistema para calculo de notas",
    descProj6: "Aplicación de consola en Python para calcular la nota final de estudiantes...",
    proj6desc1: "Desarrollé una aplicación de consola en Python para calcular la nota final de estudiantes a partir de diferentes porcentajes de evaluación.",
    proj6desc2: "El sistema solicita la información del estudiante, valida las calificaciones ingresadas y realiza el cálculo de la nota final automáticamente.",
    proj6desc3: "Además, muestra un mensaje de rendimiento según el resultado obtenido, garantizando que los datos ingresados sean válidos.",
    proj7: "Sistema para biblioteca",
    descProj7: "Aplicación web en Laravel para gestionar una biblioteca...",
    proj7desc1: "Desarrollé una aplicación web en Laravel para gestionar una biblioteca, permitiendo administrar autores y libros de forma eficiente.",
    proj7desc2: "El sistema implementa operaciones CRUD con validaciones para garantizar el correcto registro y mantenimiento de la información.",
    proj7desc3: "Además, incorpora la relación entre autores y libros, ofreciendo una estructura organizada y fácil de administrar.",
    cerrarCuadroCerts: "Presiona acá para volver.",
    python1: "Fundamentos de Python 1 - Cisco Academy",
    descPython1: "Conceptos básicos de programación y desarrollo en Python.",
    cienciaDatosFund: "Fundamentos de Análisis de Datos - Cisco Academy",
    descCienciaDatosFund: "Conceptos de análisis, interpretación y visualización de datos.",
    CCNAint: "CCNA Introducción a las redes - Cisco Academy",
    descCCNAint: "Fundamentos de redes, conectividad y comunicación de dispositivos.",
    AgileInt: "Introducción al desarrollo Agile y Scrum - Coursera",
    descAgileInt: "Principios ágiles, gestión de proyectos y metodología Scrum.",
    IoTCPT: "Explorando IoT con Cisco Packet Tracer - Cisco Academy",
    descIoTCPT: "Fundamentos de IoT y simulación de dispositivos conectados.",
    IoTyTransf: "Introducción a IoT y Transformación Digital - Cisco Academy",
    descIoTyTransf: "Conceptos de IoT y tecnologías para la transformación digital.",
    FundTI: "Fundamentos de TI - Cisco Academy",
    descFundTI: "Bases de la informática, hardware, software y redes.",
    contactame: "Contáctame",
    llamame: "Llámame o escríbeme por Whatsapp.",
    emailme: "Envíame un correo directamente.",
    githubme: "Mira mi Github."
  },
  en: {
    inicio: "Home",
    sobre: "About me",
    habilidades: "Skills",
    proyectos: "Projects",
    certificaciones: "Certifications",
    contacto: "Contact",
    desarroladorst: "Junior Software Developer.",
    desarroladorDesc: "Building reliable backends and clean systems, one line of code at a time.",
    quiensoyst: "About me",
    descripQuiensoyst: "Developer focused on building clean systems, solving problems, and turning data into decisions.",
    añosprog: "Years coding",
    projecCompl: "Completed projects",
    lenguajesCard: "Languages used",
    certificacionesCard: "Certifications",
    descrip1: "I am a junior web developer with a focus on the backend and experience in ASP.NET Core, PHP/Laravel, SQL, and computer networks. I enjoy creating organized systems, solving problems, and understanding the internal workings behind the code.",
    descrip2: "I am also interested in data science, data visualization, and financial markets. As a trader and investor in stocks and cryptocurrencies, I have strengthened my interest in data, analysis, patterns, and decision-making.",
    descrip3: "I enjoy combining software development, networking, data, and finance in my personal projects, while continuously improving my skills and growing as a developer.",
    conQueTrabajo: "What I work with",
    lenguajesStack: "Languages",
    dbtext: "Databases",
    herram: "Tools",
    cienciaDatos: "Data Science",
    loQueHe: "What I´ve built",
    proyectos: "Projects",
    proj1: "EbaisSys Academic Project",
    descProj1: "Web application for the basic management of an EBAIS...",
    verMasProj: "View more",
    verGithub: "View on GitHub",
    proj1desc1: "I developed a web application for the basic management of an EBAIS, allowing the simple and organized administration of patients and administrative processes.",
    proj1desc2: "The system implements CRUD operations with validations to ensure proper information management and maintain data integrity.",
    proj1desc3: "The application follows the MVC architecture, offering a clean, scalable, and easy-to-maintain code structure.",
    proj2: "ExpotecnicaSys Academic Project",
    descProj2: "Web application to manage and evaluate ExpoTécnica projects...",
    proj2desc1: "I developed a web application using ASP.NET Core to manage and evaluate ExpoTécnica projects, streamlining the grading process by categories.",
    proj2desc2: "The system allows judges to register evaluations, assign scores, and view results in a clear and organized manner.",
    proj2desc3: "The application was deployed to Azure with a cloud database, enabling remote access from any device.",
    proj3: "TradeForGod System (Real project)",
    descProj3: "PHP web system with MVC architecture integrated with Discord...",
    proj3desc1: "I developed a PHP web system using the MVC architecture to manage users, groups, and various internal processes through a role-based system.",
    proj3desc2: "It features Administrator, Teacher, and Student roles, along with authentication, access control, and Discord integration for user management.",
    proj3desc3: "The project is currently in the process of being migrated to Laravel, aiming to improve its scalability, maintenance, and structure.",
    proj4: "Sistema TradeForGod (Proyecto real)",
    descProj4: "Inventory and sales management system in C++ using arrays...",
    proj4desc1: "I developed an inventory and sales management system in C++, focused on managing products, suppliers, users, and customers.",
    proj4desc2: "The system implements CRUD operations and a functional sales workflow, including automated stock level updates.",
    proj4desc3: "It features a console-based interface and data management using arrays, simulating basic business processes.",
    proj5: "Network Infrastructure Project",
    descProj5: "Enterprise network infrastructure in Cisco Packet Tracer...",
    proj5desc1: "I developed an enterprise network infrastructure in Cisco Packet Tracer, simulating the connection between two sites through an Internet Service Provider.",
    proj5desc2: "The network implements segmentation via VLANs, static routing, and the HSRP protocol to ensure high availability and service continuity.",
    proj5desc3: "The project includes the IP addressing design, full network configuration, and technical documentation to facilitate its implementation.",
    proj6: "Grade Calculation System",
    descProj6: "Python console application to calculate students' final grades...",
    proj6desc1: "I developed a Python console application to calculate students' final grades based on different evaluation percentages.",
    proj6desc2: "The system requests student information, validates the entered grades, and automatically calculates the final score.",
    proj6desc3: "Additionally, it displays a performance message based on the result obtained, ensuring that the entered data is valid.",
    proj7: "Library Management System",
    descProj7: "Laravel web application to manage a library....",
    proj7desc1: "I developed a Laravel web application to manage a library, enabling the efficient administration of authors and books.",
    proj7desc2: "The system implements CRUD operations with validations to guarantee the proper registration and maintenance of information.",
    proj7desc3: "Additionally, it incorporates the relationship between authors and books, offering an organized and easy-to-manage structure.",
    cerrarCuadroCerts: "Press here to come back.",
    python1: "Python Fundamentals 1 - Cisco Academy",
    descPython1: "Basic concepts of programming and development in Python.",
    cienciaDatosFund: "Data Analysis Fundamentals - Cisco Academy",
    descCienciaDatosFund: "Concepts of data analysis, interpretation, and visualization.",
    CCNAint: "CCNA Introduction to Networks - Cisco Academy",
    descCCNAint: "Fundamentals of networking, connectivity, and device communication.",
    AgileInt: "Introduction to Agile Development and Scrum - Coursera",
    descAgileInt: "Agile principles, project management, and Scrum methodology.",
    IoTCPT: "Introducción al desarrollo Agile y Scrum - Coursera",
    descIoTCPT: "Principios ágiles, gestión de proyectos y metodología Scrum.",
    IoTCPT: "Exploring IoT with Cisco Packet Tracer - Cisco Academy",
    descIoTCPT: "Fundamentals of IoT and simulation of connected devices.",
    IoTyTransf: "Introduction to IoT and Digital Transformation - Cisco Academy",
    descIoTyTransf: "IoT concepts and technologies for digital transformation.",
    FundTI: "IT Essentials - Cisco Academy",
    descFundTI: "Basics of computer science, hardware, software, and networking.",
    contactame: "Find me",
    llamame: "Call me or send me a Whatsapp.",
    emailme: "Email me directly.",
    githubme: "See my Github."
  }
};